site_name: Tech Challenge — Obesity (Fase 4)
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
nav:
  - Início: index.md
  - Dados: dados.md
  - Modelo: modelo.md
  - App (Streamlit): app.md
  - Dashboard (Power BI): dashboard.md
  - Entrega (Links & Vídeo): entrega.md
